spring.application.name=Computadora
server.port=8001
#Conexion a la bd
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#Nombre de usuario
spring.datasource.username=ENUCOM13
#Contraseña para la conexion
spring.datasource.password=enucom
#Actualiza el esquema de la bd
spring.jpa.hibernate.ddl-auto=update
#Driver jdbc para Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#Provedor de bd
spring.jpa.database=oracle
#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#Habilitamos el formateo de SQL
spring.jpa.properties.hibernate.format-sql=true

